#!/bin/sh
set -e
TARGET_DIR=/usr/local/bin
SUDO=""
if [ $(id -u) -ne 0 ]; then
    SUDO="sudo"
fi
if ! command -v xclip; then
    echo "Installing xclip for system-wide clipboard support"
    sudo apt-get install -y xclip || true
fi
echo "Downloading affe to $TARGET_DIR"
curl -sS --fail https://raw.githubusercontent.com/Leistungsabfall/affe/refs/heads/main/bin/affe -o affe
chmod +x ./affe
$SUDO mv ./affe $TARGET_DIR/affe
affe
